// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFBiBMrqtIsz2EELkt36ZMa_2GSEW8alM',
    appId: '1:301244790323:web:41552d282c15493837d546',
    messagingSenderId: '301244790323',
    projectId: 'habit-hero-app-692d0',
    authDomain: 'habit-hero-app-692d0.firebaseapp.com',
    storageBucket: 'habit-hero-app-692d0.firebasestorage.app',
    measurementId: 'G-RPR8SE1B98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTLDZKz6WWjyN_4HVfLJU9j1dfVpkoAM',
    appId: '1:301244790323:android:2a7a711e65e2a3d937d546',
    messagingSenderId: '301244790323',
    projectId: 'habit-hero-app-692d0',
    storageBucket: 'habit-hero-app-692d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZiKfyH9Z6bP9iXwqL1o87Cu__SBnVx6A',
    appId: '1:301244790323:ios:f473bf69b45580b637d546',
    messagingSenderId: '301244790323',
    projectId: 'habit-hero-app-692d0',
    storageBucket: 'habit-hero-app-692d0.firebasestorage.app',
    iosBundleId: 'com.example.habitHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZiKfyH9Z6bP9iXwqL1o87Cu__SBnVx6A',
    appId: '1:301244790323:ios:f473bf69b45580b637d546',
    messagingSenderId: '301244790323',
    projectId: 'habit-hero-app-692d0',
    storageBucket: 'habit-hero-app-692d0.firebasestorage.app',
    iosBundleId: 'com.example.habitHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFBiBMrqtIsz2EELkt36ZMa_2GSEW8alM',
    appId: '1:301244790323:web:c4ec857537f27b0137d546',
    messagingSenderId: '301244790323',
    projectId: 'habit-hero-app-692d0',
    authDomain: 'habit-hero-app-692d0.firebaseapp.com',
    storageBucket: 'habit-hero-app-692d0.firebasestorage.app',
    measurementId: 'G-3DYWJ2XG70',
  );
}
